apiVersion: v1
kind: Pod
metadata:
  name: guaranteed
  namespace: qos-example
spec:
  containers:
    - name: qos-demo-ctr
      image: nginx
      resources:
        limits:
          memory: 50Mi
          cpu: 100m
        requests:
          memory: 50Mi
          cpu: 100m
