apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: debug-namespace
  namespace: infra-argocd
spec:
  project: training
  source:
    repoURL: https://github.com/mueller-tobias/k8s-training-examples.git
    targetRevision: main
    path: 12_debugging/examples
    directory:
      recurse: false
      include: '00-namespace.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: example-debugging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
