apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  namespace: networking-example
spec:
  # type of the service (default ClusterIP)
  type: ClusterIP
  # ports assigned to this service
  ports:
    - port: 8080
      protocol: TCP
      name: web
      targetPort: 80
  # selector for the assigned pods
  selector:
    run: my-nginx
