apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-app
  namespace: rolling-updates
spec:
  ingressClassName: nginx
  rules:
    - host: rollingupdates.bader.demo.k8s-lab.de
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: demo-app
                port:
                  name: web
