# Single Secret key/value usage inside ENV
apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
  namespace: config-example
spec:
  restartPolicy: Never
  containers:
    - name: mycontainer
      image: redis
      resources:
        limits:
          cpu: 100m
          memory: 10Mi
      env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: wordpressdb
              key: hostname
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: wordpressdb
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpressdb
              key: password
---
# Use secret as volume
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: config-example
spec:
  containers:
    - name: mypod
      image: redis
      resources:
        limits:
          cpu: 100m
          memory: 10Mi
      volumeMounts:
        - name: foo
          mountPath: /etc/foo
  volumes:
    - name: foo
      secret:
        secretName: mysecret
# After creating keys are files with values as content
# /etc/foo/key -> value
# /etc/foo/other-key -> other-value
