apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: nginx
          image: nginx:latest
          resources: {}
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: www-data
          ports:
            - containerPort: 80
              name: web
              protocol: TCP
      volumes:
        - name: www-data
          persistentVolumeClaim:
            claimName: nginx-volume
