apiVersion: v1
kind: Pod
metadata:
  name: configmap-volume-pod
  namespace: config-example
spec:
  restartPolicy: Never
  containers:
    - name: test-container
      image: busybox
      resources:
        limits:
          cpu: 100m
          memory: 100M
      command:
        [
          "/bin/sh",
          "-c",
          "sleep inf",
        ]
      volumeMounts:
        - name: config-volume
          # Caution: If there are some files in the /etc/config/ directory, they will be overwritten.
          mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        # Provide the name of the ConfigMap containing the files you want
        # to add to the container
        name: test-config
        # items:
        #   - key: configKey
        #     path: config-key-path.xxx
