apiVersion: v1
kind: Pod
metadata:
  name: test-empty-dir
spec:
  containers:
    - image: nginx
      name: test-container
      resources:
        limits:
          cpu: 100m
          memory: 25Mi
      volumeMounts:
        - mountPath: /cache
          name: cache
  volumes:
    - name: cache
      emptyDir: {}
