apiVersion: v1
kind: Pod
metadata:
  name: test-hostpath
spec:
  containers:
    - image: nginx
      name: test-container
      resources:
        limits:
          cpu: 100m
          memory: 25Mi
      volumeMounts:
        - mountPath: /host-logs
          name: test-volume
          # readOnly: true
  volumes:
    - name: test-volume
      hostPath:
        # directory location on host
        path: /var/log
        # this field is optional
        type: DirectoryOrCreate
