apiVersion: v1
kind: Pod
metadata:
  name: resource-example
  namespace: mem-example
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          cpu: 10m
          memory: 28Mi
        limits:
          cpu: 100m
          memory: 56Mi
