apiVersion: v1
kind: Pod
metadata:
  name: init-pod
  labels:
    app: init-pod
spec:
  initContainers:
    - name: init
      image: busybox
      command:
        ["sh", "-c", 'echo "Init Start" && sleep 10 && echo "Init complete"']
  containers:
    - name: application
      image: busybox
      command: ["sh", "-c", "echo Hello Kubernetes! && sleep 3600"]
