apiVersion: v1
kind: Pod
metadata:
  name: sidecar-pod
  labels:
    app: sidecar-pod
spec:
  containers:
    - name: application
      image: busybox
      command: ["sh", "-c", "echo Hello Kubernetes! && sleep 3600"]
    - name: sidecar
      image: busybox
      command: ["sh", "-c", "echo Sidecar! && sleep 3600"]
