apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: training
  namespace: argocd
spec:
  description: Lindner k8s training examples
  sourceRepos:
    - https://github.com/mueller-tobias/k8s-training-examples.git
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
