apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  # Crontab configuration - in this case run every minute
  schedule: "*/1 * * * *"
  # Allow concurrency running of jobs if previous job is not finished
  # possible values: Allow, Forbid (skip on existing job run), Replace (delete/cancel current job and start new one)
  concurrencyPolicy: Allow
  # Disable the cronjob if suspend is set to true
  suspend: false
  # how many succesfull jobs should be kept
  successfulJobsHistoryLimit: 3
  # how many failed jobs should be kept
  failedJobsHistoryLimit: 1
  jobTemplate:
    # normal "job" spec
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: busybox
              args:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
