apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db # has to match .spec.template.metadata.labels
  serviceName: db
  replicas: 3
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: db # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 31
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
              name: web
